"""
Automated regression tests for the frontend pipeline.

The models under models/ are generated by the make_*.py scripts in this
same folder (run once, checked in so tests don't depend on generation
order). These tests replace eyeballing main.py's console output with real
assertions, so a regression in legalize/shape_infer/verify fails a test
run instead of only being caught by someone reading the log by hand.
"""

import os

import numpy as np
import pytest

from frontend import pipeline
from frontend.legalize import legalize

MODELS_DIR = os.path.join(os.path.dirname(__file__), "..", "models")


def _model_path(name):
    return os.path.join(MODELS_DIR, name)


def _naive_conv2d(x, w, b, pad):
    N, Cin, H, W_ = x.shape
    Cout, _, kh, kw = w.shape
    xp = np.pad(x, ((0, 0), (0, 0), (pad, pad), (pad, pad)))
    out = np.zeros((N, Cout, H, W_), dtype=np.float32)
    for oy in range(H):
        for ox in range(W_):
            patch = xp[:, :, oy:oy + kh, ox:ox + kw]
            for co in range(Cout):
                out[:, co, oy, ox] = np.sum(patch * w[co], axis=(1, 2, 3)) + b[co]
    return out


def test_tiny_conv_shape():
    graph = pipeline.run(_model_path("tiny_conv.onnx"), verbose=False)
    conv_nodes = [n for n in graph.nodes if n.op_type == "Conv2D"]
    assert len(conv_nodes) == 1
    assert conv_nodes[0].outputs[0].shape == (1, 4, 8, 8)


def test_convbn_fold_matches_manual_conv_bn():
    graph = pipeline.run(_model_path("convbn.onnx"), verbose=False)

    op_types = [n.op_type for n in graph.nodes]
    assert "BatchNormalization" not in op_types
    conv_nodes = [n for n in graph.nodes if n.op_type == "Conv2D"]
    assert len(conv_nodes) == 1

    conv = conv_nodes[0]
    folded_W = graph.initializers[conv.inputs[1].name]
    folded_b = graph.initializers[conv.inputs[2].name]

    ref = np.load(_model_path("convbn_ref.npz"))
    x, W, gamma, beta, mean, var = ref["x"], ref["W"], ref["gamma"], ref["beta"], ref["mean"], ref["var"]

    unfolded = _naive_conv2d(x, W, np.zeros(W.shape[0], dtype=np.float32), pad=1)
    eps = 1e-5
    bn_out = gamma.reshape(1, -1, 1, 1) * (unfolded - mean.reshape(1, -1, 1, 1)) / np.sqrt(
        var.reshape(1, -1, 1, 1) + eps) + beta.reshape(1, -1, 1, 1)
    expected = np.maximum(bn_out, 0)

    folded = np.maximum(_naive_conv2d(x, folded_W, folded_b, pad=1), 0)

    assert np.allclose(expected, folded, atol=1e-4)


def test_residual_block_structure():
    graph = pipeline.run(_model_path("residual_block.onnx"), verbose=False)

    op_types = [n.op_type for n in graph.nodes if n.op_type != "Constant"]
    assert op_types.count("Conv2D") == 2
    assert op_types.count("Add") == 1
    assert op_types.count("ReLU") == 2
    assert "BatchNormalization" not in op_types

    add_node = next(n for n in graph.nodes if n.op_type == "Add")
    assert add_node.outputs[0].shape == (1, 4, 8, 8)


def test_unsupported_op_is_rejected():
    graph = pipeline.import_model(pipeline.validate(_model_path("unsupported_op.onnx")))
    with pytest.raises(ValueError, match="Sigmoid"):
        legalize(graph)
